title: “The Legend of Zelda” Ocarina Sheet Music
baseurl: /lilypond-ocarina-zelda
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-ocarina-zelda
lang: en-US
show_downloads: false
copyright: true
# Build settings
theme: jekyll-theme-minimal
plugins: []
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "a3"
    values:
      a3: true
  - scope:
      path: "tabloid"
    values:
      tabloid: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
  - scope:
      path: "video"
    values:
      video: true
